erDiagram
    Vehicle_Fact_MASTER {
        ModelName string
        VIN string
        ServiceType string
        VariantName string
        FuelType string
        VehicleChannel string
        ManufactureYear decimal
        SalePrice decimal
        ServiceDate decimal
        ServiceCost decimal
    }
    Dealer_Master {
        DealerID_ServiceID decimal
        DealerName string
        City string
        Phone string
        Email string
    }
    Model_Master {
        ModelName string
        Model_Master_ModelID decimal
    }
    Service_History {
        ServiceType string
        DealerID_ServiceID decimal
        VehicleID decimal
        Service_History_ServiceDate decimal
        Service_History_ServiceCost decimal
    }
    Variant_Master {
        VariantName string
        VariantID decimal
        Variant_Master_ModelID decimal
    }
    VIN_Details {
        VIN string
        EngineNumber string
        ChassisNumber string
        ProductionPlant string
        ProductionDate decimal
    }
    Vehicle_Fact_MASTER }o--|| Model_Master : "95%"
    Vehicle_Fact_MASTER }o--|| Service_History : "95%"
    Vehicle_Fact_MASTER }o--|| Variant_Master : "95%"
    Vehicle_Fact_MASTER }o--|| VIN_Details : "95%"
    Dealer_Master }o--|| Service_History : "75%"