CORRECTED M QUERY FOR POWER BI
===============================

// 
// Table: Dates [csv] - FIXED DERIVED COLUMNS
// 
let
    SiteUrl = "https://sorimtechnologies.sharepoint.com",
    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),
    Filtered = Table.SelectRows(
        Source,
        each
            Text.EndsWith(Text.Lower([Name]), "dim_date.csv") and
            Text.Contains(Text.Lower([Folder Path]), "shared documents")
    ),
    File = if Table.RowCount(Filtered) > 0
        then Filtered{0}[Content]
        else error "File dim_date.csv not found in SharePoint",
    Csv = Csv.Document(File, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),
    TypedTable = Table.TransformColumnTypes(
        Headers,
        {
        {"date_id", type text}
        }
    ),
    // Convert date_id string (YYYYMMDD) to actual date
    #"Added full_date" = Table.AddColumn(
        TypedTable,
        "full_date",
        each Date.FromText([date_id], "YYYYMMDD"),
        type date
    ),
    // Extract Year from the converted date
    #"Added year" = Table.AddColumn(
        #"Added full_date",
        "year",
        each Date.Year([full_date]),
        type number
    ),
    // Extract Month from the converted date
    #"Added month" = Table.AddColumn(
        #"Added year",
        "month",
        each Date.Month([full_date]),
        type number
    ),
    // Extract Day from the converted date
    #"Added day" = Table.AddColumn(
        #"Added month",
        "day",
        each Date.Day([full_date]),
        type number
    ),
    // Calculate Quarter from Month
    #"Added quarter" = Table.AddColumn(
        #"Added day",
        "quarter",
        each "Q" & Text.From(Number.RoundUp(Date.Month([full_date]) / 3)),
        type text
    )
in
    #"Added quarter"

// 
// Table: Final_Activity [resident] - FIXED MISSING DERIVED COLUMNS
// 
let
    SiteUrl = "https://sorimtechnologies.sharepoint.com",
    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),
    Filtered = Table.SelectRows(
        Source,
        each
            Text.EndsWith(Text.Lower([Name]), "fact_employee_activity_1m.csv") and
            Text.Contains(Text.Lower([Folder Path]), "shared documents")
    ),
    File = if Table.RowCount(Filtered) > 0
        then Filtered{0}[Content]
        else error "File fact_employee_activity_1M.csv not found in SharePoint",
    Csv = Csv.Document(File, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),
    // Handle null hours_worked
    #"Replaced null hours" = Table.ReplaceValue(
        Headers,
        null,
        0,
        Replacer.ReplaceValue,
        {"hours_worked"}
    ),
    // Add work_type: If(hours_worked > 8, 'Overtime', 'Normal')
    #"Added work_type" = Table.AddColumn(
        #"Replaced null hours",
        "work_type",
        each if [hours_worked] > 8 then "Overtime" else "Normal",
        type text
    ),
    // Add productivity_flag: If(hours_worked >= 8, 1, 0)
    #"Added productivity_flag" = Table.AddColumn(
        #"Added work_type",
        "productivity_flag",
        each if [hours_worked] >= 8 then 1 else 0,
        type number
    ),
    // Add productivity_score: hours_worked * 10
    #"Added productivity_score" = Table.AddColumn(
        #"Added productivity_flag",
        "productivity_score",
        each [hours_worked] * 10,
        type number
    )
in
    #"Added productivity_score"

// 
// Table: Employees [csv] - KEEP AS IS (already correct)
// 
let
    SiteUrl = "https://sorimtechnologies.sharepoint.com",
    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),
    Filtered = Table.SelectRows(
        Source,
        each
            Text.EndsWith(Text.Lower([Name]), "dim_employee.csv") and
            Text.Contains(Text.Lower([Folder Path]), "shared documents")
    ),
    File = if Table.RowCount(Filtered) > 0
        then Filtered{0}[Content]
        else error "File dim_employee.csv not found in SharePoint",
    Csv = Csv.Document(File, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),
    TypedTable = Table.TransformColumnTypes(
        Headers,
        {
        {"employee_id", type text},
        {"department_id", type text},
        {"role_id", type text},
        {"location_id", type text},
        {"salary_band_id", type text}
        }
    ),
    // Trim and uppercase employee_name
    #"Added employee_name" = Table.AddColumn(
        TypedTable,
        "employee_name",
        each Text.Upper(Text.Trim([employee_name])),
        type text
    ),
    // Left join with Departments for ApplyMap logic
    MergedDepartments = Table.NestedJoin(
        #"Added employee_name",
        {"department_id"},
        Departments,
        {"department_id"},
        "Departments",
        JoinKind.LeftOuter
    ),
    ExpandedDepartments = Table.ExpandTableColumn(
        MergedDepartments,
        "Departments",
        {"department_name"},
        {"emp_department_name"}
    ),
    // Fill null with "Unknown"
    Filledemp_department_name = Table.ReplaceValue(
        ExpandedDepartments,
        null,
        "Unknown",
        Replacer.ReplaceValue,
        {"emp_department_name"}
    )
in
    Filledemp_department_name

// All other tables (Departments, Locations, Projects, Clients, Roles, Salary, Performance, Shift)
// remain as LOAD * - keep them as is (already correct in your M Query)
