{
  "name": "Employees",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Employees",
        "columns": [
          {
            "name": "employee_id",
            "dataType": "string",
            "sourceColumn": "employee_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "department_id",
            "dataType": "string",
            "sourceColumn": "department_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "role_id",
            "dataType": "string",
            "sourceColumn": "role_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "location_id",
            "dataType": "string",
            "sourceColumn": "location_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "salary_band_id",
            "dataType": "string",
            "sourceColumn": "salary_band_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Employees-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"dim_employee.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        PromotedHeaders,",
                "        {",
                "        {\"employee_id\", type text},",
                "        {\"department_id\", type text},",
                "        {\"role_id\", type text},",
                "        {\"location_id\", type text},",
                "        {\"salary_band_id\", type text}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "Departments",
        "columns": [
          {
            "name": "Value",
            "dataType": "string",
            "sourceColumn": "Value",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Departments-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"dim_department.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true])",
                "in",
                "    PromotedHeaders"
              ]
            }
          }
        ]
      },
      {
        "name": "Locations",
        "columns": [
          {
            "name": "Value",
            "dataType": "string",
            "sourceColumn": "Value",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Locations-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"dim_location.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true])",
                "in",
                "    PromotedHeaders"
              ]
            }
          }
        ]
      },
      {
        "name": "Projects",
        "columns": [
          {
            "name": "Value",
            "dataType": "string",
            "sourceColumn": "Value",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Projects-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"dim_project.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true])",
                "in",
                "    PromotedHeaders"
              ]
            }
          }
        ]
      },
      {
        "name": "Clients",
        "columns": [
          {
            "name": "Value",
            "dataType": "string",
            "sourceColumn": "Value",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Clients-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"dim_client.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true])",
                "in",
                "    PromotedHeaders"
              ]
            }
          }
        ]
      },
      {
        "name": "Roles",
        "columns": [
          {
            "name": "Value",
            "dataType": "string",
            "sourceColumn": "Value",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Roles-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"dim_role.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true])",
                "in",
                "    PromotedHeaders"
              ]
            }
          }
        ]
      },
      {
        "name": "Salary",
        "columns": [
          {
            "name": "Value",
            "dataType": "string",
            "sourceColumn": "Value",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Salary-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"dim_salary_band.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true])",
                "in",
                "    PromotedHeaders"
              ]
            }
          }
        ]
      },
      {
        "name": "Performance",
        "columns": [
          {
            "name": "Value",
            "dataType": "string",
            "sourceColumn": "Value",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Performance-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"dim_performance.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true])",
                "in",
                "    PromotedHeaders"
              ]
            }
          }
        ]
      },
      {
        "name": "Shift",
        "columns": [
          {
            "name": "Value",
            "dataType": "string",
            "sourceColumn": "Value",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Shift-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"dim_shift.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true])",
                "in",
                "    PromotedHeaders"
              ]
            }
          }
        ]
      },
      {
        "name": "Dates",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dates-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"dim_date.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        PromotedHeaders,",
                "        {",
                "        {\"date_id\", type text}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_employee_activity_1M",
        "columns": [
          {
            "name": "employee_id",
            "dataType": "string",
            "sourceColumn": "employee_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "project_id",
            "dataType": "string",
            "sourceColumn": "project_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "performance_id",
            "dataType": "string",
            "sourceColumn": "performance_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "shift_id",
            "dataType": "string",
            "sourceColumn": "shift_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fact_employee_activity_1M-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"fact_employee_activity_1M.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        PromotedHeaders,",
                "        {",
                "        {\"employee_id\", type text},",
                "        {\"project_id\", type text},",
                "        {\"date_id\", type text},",
                "        {\"performance_id\", type text},",
                "        {\"shift_id\", type text}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "Final_Activity",
        "columns": [
          {
            "name": "Value",
            "dataType": "string",
            "sourceColumn": "Value",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Final_Activity-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"fact_employee_activity_1M.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true]),",
                "    Add_productivity_score = Table.AddColumn(",
                "        PromotedHeaders,",
                "        \"productivity_score\",",
                "        each [hours_worked] * 10,",
                "        type number",
                "    )",
                "in",
                "    Add_productivity_score"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "fact_employee_activity_1M_employee_id_Employees_employee_id",
        "fromTable": "fact_employee_activity_1M",
        "fromColumn": "employee_id",
        "toTable": "Employees",
        "toColumn": "employee_id",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "fact_employee_activity_1M_date_id_Dates_date_id",
        "fromTable": "fact_employee_activity_1M",
        "fromColumn": "date_id",
        "toTable": "Dates",
        "toColumn": "date_id",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "DataSourcePath",
        "kind": "m",
        "expression": [
          "\"https://sorimtechnologies.sharepoint.com\""
        ],
        "annotations": [
          {
            "name": "IsParameterQuery",
            "value": "True"
          },
          {
            "name": "IsParameterQueryRequired",
            "value": "False"
          },
          {
            "name": "PBI_QueryOrder",
            "value": "0"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0"
      },
      {
        "name": "createdBy",
        "value": "QlikAI_Accelerator"
      }
    ]
  }
}