{
  "name": "Vehicle_Fact_MASTER",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Vehicle_Fact_MASTER",
        "columns": [
          {
            "name": "ModelName",
            "dataType": "string",
            "sourceColumn": "ModelName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "VIN",
            "dataType": "string",
            "sourceColumn": "VIN",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ServiceType",
            "dataType": "string",
            "sourceColumn": "ServiceType",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "VariantName",
            "dataType": "string",
            "sourceColumn": "VariantName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FuelType",
            "dataType": "string",
            "sourceColumn": "FuelType",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "VehicleChannel",
            "dataType": "string",
            "sourceColumn": "VehicleChannel",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ManufactureYear",
            "dataType": "string",
            "sourceColumn": "ManufactureYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SalePrice",
            "dataType": "string",
            "sourceColumn": "SalePrice",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ServiceDate",
            "dataType": "string",
            "sourceColumn": "ServiceDate",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ServiceCost",
            "dataType": "string",
            "sourceColumn": "ServiceCost",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Vehicle_Fact_MASTER-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"vehicle_fact_master.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File Vehicle_Fact_MASTER.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"VIN\", type text},",
                "        {\"ModelName\", type text},",
                "        {\"VariantName\", type text},",
                "        {\"FuelType\", type text},",
                "        {\"VehicleChannel\", type text},",
                "        {\"ManufactureYear\", Int64.Type},",
                "        {\"SalePrice\", type number},",
                "        {\"ServiceDate\", type date},",
                "        {\"ServiceType\", type text},",
                "        {\"ServiceCost\", type number}",
                "        }",
                "    ),",
                "    #\"Derived VIN\" = Table.AddColumn(",
                "        TypedTable,",
                "        \"VIN__derived\",",
                "        each [VIN], type text",
                "    ),",
                "    #\"Removed original VIN\" = Table.RemoveColumns(",
                "        #\"Derived VIN\",",
                "        {\"VIN\"}",
                "    ),",
                "    #\"Replaced VIN\" = Table.RenameColumns(",
                "        #\"Removed original VIN\",",
                "        {",
                "            {\"VIN__derived\", \"VIN\"}",
                "        }",
                "    ),",
                "    #\"Derived ModelName\" = Table.AddColumn(",
                "        #\"Replaced VIN\",",
                "        \"ModelName__derived\",",
                "        each [ModelName], type text",
                "    ),",
                "    #\"Removed original ModelName\" = Table.RemoveColumns(",
                "        #\"Derived ModelName\",",
                "        {\"ModelName\"}",
                "    ),",
                "    #\"Replaced ModelName\" = Table.RenameColumns(",
                "        #\"Removed original ModelName\",",
                "        {",
                "            {\"ModelName__derived\", \"ModelName\"}",
                "        }",
                "    ),",
                "    #\"Derived VariantName\" = Table.AddColumn(",
                "        #\"Replaced ModelName\",",
                "        \"VariantName__derived\",",
                "        each [VariantName], type text",
                "    ),",
                "    #\"Removed original VariantName\" = Table.RemoveColumns(",
                "        #\"Derived VariantName\",",
                "        {\"VariantName\"}",
                "    ),",
                "    #\"Replaced VariantName\" = Table.RenameColumns(",
                "        #\"Removed original VariantName\",",
                "        {",
                "            {\"VariantName__derived\", \"VariantName\"}",
                "        }",
                "    ),",
                "    #\"Derived FuelType\" = Table.AddColumn(",
                "        #\"Replaced VariantName\",",
                "        \"FuelType__derived\",",
                "        each [FuelType], type text",
                "    ),",
                "    #\"Removed original FuelType\" = Table.RemoveColumns(",
                "        #\"Derived FuelType\",",
                "        {\"FuelType\"}",
                "    ),",
                "    #\"Replaced FuelType\" = Table.RenameColumns(",
                "        #\"Removed original FuelType\",",
                "        {",
                "            {\"FuelType__derived\", \"FuelType\"}",
                "        }",
                "    ),",
                "    #\"Derived VehicleChannel\" = Table.AddColumn(",
                "        #\"Replaced FuelType\",",
                "        \"VehicleChannel__derived\",",
                "        each [VehicleChannel], type text",
                "    ),",
                "    #\"Removed original VehicleChannel\" = Table.RemoveColumns(",
                "        #\"Derived VehicleChannel\",",
                "        {\"VehicleChannel\"}",
                "    ),",
                "    #\"Replaced VehicleChannel\" = Table.RenameColumns(",
                "        #\"Removed original VehicleChannel\",",
                "        {",
                "            {\"VehicleChannel__derived\", \"VehicleChannel\"}",
                "        }",
                "    ),",
                "    #\"Derived ManufactureYear\" = Table.AddColumn(",
                "        #\"Replaced VehicleChannel\",",
                "        \"ManufactureYear__derived\",",
                "        each [ManufactureYear], type text",
                "    ),",
                "    #\"Removed original ManufactureYear\" = Table.RemoveColumns(",
                "        #\"Derived ManufactureYear\",",
                "        {\"ManufactureYear\"}",
                "    ),",
                "    #\"Replaced ManufactureYear\" = Table.RenameColumns(",
                "        #\"Removed original ManufactureYear\",",
                "        {",
                "            {\"ManufactureYear__derived\", \"ManufactureYear\"}",
                "        }",
                "    ),",
                "    #\"Derived SalePrice\" = Table.AddColumn(",
                "        #\"Replaced ManufactureYear\",",
                "        \"SalePrice__derived\",",
                "        each [SalePrice], type text",
                "    ),",
                "    #\"Removed original SalePrice\" = Table.RemoveColumns(",
                "        #\"Derived SalePrice\",",
                "        {\"SalePrice\"}",
                "    ),",
                "    #\"Replaced SalePrice\" = Table.RenameColumns(",
                "        #\"Removed original SalePrice\",",
                "        {",
                "            {\"SalePrice__derived\", \"SalePrice\"}",
                "        }",
                "    ),",
                "    #\"Derived ServiceDate\" = Table.AddColumn(",
                "        #\"Replaced SalePrice\",",
                "        \"ServiceDate__derived\",",
                "        each [ServiceDate], type text",
                "    ),",
                "    #\"Removed original ServiceDate\" = Table.RemoveColumns(",
                "        #\"Derived ServiceDate\",",
                "        {\"ServiceDate\"}",
                "    ),",
                "    #\"Replaced ServiceDate\" = Table.RenameColumns(",
                "        #\"Removed original ServiceDate\",",
                "        {",
                "            {\"ServiceDate__derived\", \"ServiceDate\"}",
                "        }",
                "    ),",
                "    #\"Derived ServiceType\" = Table.AddColumn(",
                "        #\"Replaced ServiceDate\",",
                "        \"ServiceType__derived\",",
                "        each [ServiceType], type text",
                "    ),",
                "    #\"Removed original ServiceType\" = Table.RemoveColumns(",
                "        #\"Derived ServiceType\",",
                "        {\"ServiceType\"}",
                "    ),",
                "    #\"Replaced ServiceType\" = Table.RenameColumns(",
                "        #\"Removed original ServiceType\",",
                "        {",
                "            {\"ServiceType__derived\", \"ServiceType\"}",
                "        }",
                "    ),",
                "    #\"Derived ServiceCost\" = Table.AddColumn(",
                "        #\"Replaced ServiceType\",",
                "        \"ServiceCost__derived\",",
                "        each [ServiceCost], type text",
                "    ),",
                "    #\"Removed original ServiceCost\" = Table.RemoveColumns(",
                "        #\"Derived ServiceCost\",",
                "        {\"ServiceCost\"}",
                "    ),",
                "    #\"Replaced ServiceCost\" = Table.RenameColumns(",
                "        #\"Removed original ServiceCost\",",
                "        {",
                "            {\"ServiceCost__derived\", \"ServiceCost\"}",
                "        }",
                "    )",
                "in",
                "    #\"Replaced ServiceCost\""
              ]
            }
          }
        ]
      },
      {
        "name": "Dealer_Master",
        "columns": [
          {
            "name": "DealerID-ServiceID",
            "dataType": "string",
            "sourceColumn": "DealerID-ServiceID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DealerName",
            "dataType": "string",
            "sourceColumn": "DealerName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Email",
            "dataType": "string",
            "sourceColumn": "Email",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dealer_Master-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dealer_master.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File Dealer_Master.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"DealerID\", type text},",
                "        {\"DealerName\", type text},",
                "        {\"City\", type text},",
                "        {\"Phone\", type text},",
                "        {\"Email\", type text}",
                "        }",
                "    ),",
                "    #\"Added DealerID-ServiceID\" = Table.AddColumn(",
                "        TypedTable,",
                "        \"DealerID-ServiceID\",",
                "        each [DealerID], type text",
                "    ),",
                "    #\"Derived DealerName\" = Table.AddColumn(",
                "        #\"Added DealerID-ServiceID\",",
                "        \"DealerName__derived\",",
                "        each [DealerName], type text",
                "    ),",
                "    #\"Removed original DealerName\" = Table.RemoveColumns(",
                "        #\"Derived DealerName\",",
                "        {\"DealerName\"}",
                "    ),",
                "    #\"Replaced DealerName\" = Table.RenameColumns(",
                "        #\"Removed original DealerName\",",
                "        {",
                "            {\"DealerName__derived\", \"DealerName\"}",
                "        }",
                "    ),",
                "    #\"Derived City\" = Table.AddColumn(",
                "        #\"Replaced DealerName\",",
                "        \"City__derived\",",
                "        each [City], type text",
                "    ),",
                "    #\"Removed original City\" = Table.RemoveColumns(",
                "        #\"Derived City\",",
                "        {\"City\"}",
                "    ),",
                "    #\"Replaced City\" = Table.RenameColumns(",
                "        #\"Removed original City\",",
                "        {",
                "            {\"City__derived\", \"City\"}",
                "        }",
                "    ),",
                "    #\"Derived Phone\" = Table.AddColumn(",
                "        #\"Replaced City\",",
                "        \"Phone__derived\",",
                "        each [Phone], type text",
                "    ),",
                "    #\"Removed original Phone\" = Table.RemoveColumns(",
                "        #\"Derived Phone\",",
                "        {\"Phone\"}",
                "    ),",
                "    #\"Replaced Phone\" = Table.RenameColumns(",
                "        #\"Removed original Phone\",",
                "        {",
                "            {\"Phone__derived\", \"Phone\"}",
                "        }",
                "    ),",
                "    #\"Derived Email\" = Table.AddColumn(",
                "        #\"Replaced Phone\",",
                "        \"Email__derived\",",
                "        each [Email], type text",
                "    ),",
                "    #\"Removed original Email\" = Table.RemoveColumns(",
                "        #\"Derived Email\",",
                "        {\"Email\"}",
                "    ),",
                "    #\"Replaced Email\" = Table.RenameColumns(",
                "        #\"Removed original Email\",",
                "        {",
                "            {\"Email__derived\", \"Email\"}",
                "        }",
                "    )",
                "in",
                "    #\"Replaced Email\""
              ]
            }
          }
        ]
      },
      {
        "name": "Model_Master",
        "columns": [
          {
            "name": "ModelName",
            "dataType": "string",
            "sourceColumn": "ModelName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Model_Master.ModelID",
            "dataType": "string",
            "sourceColumn": "Model_Master.ModelID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Model_Master-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"model_master.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File Model_Master.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"ModelID\", type text},",
                "        {\"ModelName\", type text}",
                "        }",
                "    ),",
                "    #\"Added Model_Master.ModelID\" = Table.AddColumn(",
                "        TypedTable,",
                "        \"Model_Master.ModelID\",",
                "        each [ModelID], type text",
                "    ),",
                "    #\"Derived ModelName\" = Table.AddColumn(",
                "        #\"Added Model_Master.ModelID\",",
                "        \"ModelName__derived\",",
                "        each [ModelName], type text",
                "    ),",
                "    #\"Removed original ModelName\" = Table.RemoveColumns(",
                "        #\"Derived ModelName\",",
                "        {\"ModelName\"}",
                "    ),",
                "    #\"Replaced ModelName\" = Table.RenameColumns(",
                "        #\"Removed original ModelName\",",
                "        {",
                "            {\"ModelName__derived\", \"ModelName\"}",
                "        }",
                "    )",
                "in",
                "    #\"Replaced ModelName\""
              ]
            }
          }
        ]
      },
      {
        "name": "Service_History",
        "columns": [
          {
            "name": "ServiceType",
            "dataType": "string",
            "sourceColumn": "ServiceType",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DealerID-ServiceID",
            "dataType": "string",
            "sourceColumn": "DealerID-ServiceID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "VehicleID",
            "dataType": "string",
            "sourceColumn": "VehicleID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Service_History.ServiceDate",
            "dataType": "string",
            "sourceColumn": "Service_History.ServiceDate",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Service_History.ServiceCost",
            "dataType": "string",
            "sourceColumn": "Service_History.ServiceCost",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Service_History-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"service_history.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File Service_History.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"ServiceID\", type text},",
                "        {\"VehicleID\", type text},",
                "        {\"ServiceDate\", type date},",
                "        {\"ServiceType\", type text},",
                "        {\"ServiceCost\", type number}",
                "        }",
                "    ),",
                "    #\"Added DealerID-ServiceID\" = Table.AddColumn(",
                "        TypedTable,",
                "        \"DealerID-ServiceID\",",
                "        each [ServiceID], type text",
                "    ),",
                "    #\"Derived VehicleID\" = Table.AddColumn(",
                "        #\"Added DealerID-ServiceID\",",
                "        \"VehicleID__derived\",",
                "        each [VehicleID], type text",
                "    ),",
                "    #\"Removed original VehicleID\" = Table.RemoveColumns(",
                "        #\"Derived VehicleID\",",
                "        {\"VehicleID\"}",
                "    ),",
                "    #\"Replaced VehicleID\" = Table.RenameColumns(",
                "        #\"Removed original VehicleID\",",
                "        {",
                "            {\"VehicleID__derived\", \"VehicleID\"}",
                "        }",
                "    ),",
                "    #\"Added Service_History.ServiceDate\" = Table.AddColumn(",
                "        #\"Replaced VehicleID\",",
                "        \"Service_History.ServiceDate\",",
                "        each [ServiceDate], type text",
                "    ),",
                "    #\"Derived ServiceType\" = Table.AddColumn(",
                "        #\"Added Service_History.ServiceDate\",",
                "        \"ServiceType__derived\",",
                "        each [ServiceType], type text",
                "    ),",
                "    #\"Removed original ServiceType\" = Table.RemoveColumns(",
                "        #\"Derived ServiceType\",",
                "        {\"ServiceType\"}",
                "    ),",
                "    #\"Replaced ServiceType\" = Table.RenameColumns(",
                "        #\"Removed original ServiceType\",",
                "        {",
                "            {\"ServiceType__derived\", \"ServiceType\"}",
                "        }",
                "    ),",
                "    #\"Added Service_History.ServiceCost\" = Table.AddColumn(",
                "        #\"Replaced ServiceType\",",
                "        \"Service_History.ServiceCost\",",
                "        each [ServiceCost], type text",
                "    )",
                "in",
                "    #\"Added Service_History.ServiceCost\""
              ]
            }
          }
        ]
      },
      {
        "name": "Variant_Master",
        "columns": [
          {
            "name": "VariantName",
            "dataType": "string",
            "sourceColumn": "VariantName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "VariantID",
            "dataType": "string",
            "sourceColumn": "VariantID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Variant_Master.ModelID",
            "dataType": "string",
            "sourceColumn": "Variant_Master.ModelID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Variant_Master-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"variant_master.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File Variant_Master.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"VariantID\", type text},",
                "        {\"ModelID\", type text},",
                "        {\"VariantName\", type text}",
                "        }",
                "    ),",
                "    #\"Derived VariantID\" = Table.AddColumn(",
                "        TypedTable,",
                "        \"VariantID__derived\",",
                "        each [VariantID], type text",
                "    ),",
                "    #\"Removed original VariantID\" = Table.RemoveColumns(",
                "        #\"Derived VariantID\",",
                "        {\"VariantID\"}",
                "    ),",
                "    #\"Replaced VariantID\" = Table.RenameColumns(",
                "        #\"Removed original VariantID\",",
                "        {",
                "            {\"VariantID__derived\", \"VariantID\"}",
                "        }",
                "    ),",
                "    #\"Added Variant_Master.ModelID\" = Table.AddColumn(",
                "        #\"Replaced VariantID\",",
                "        \"Variant_Master.ModelID\",",
                "        each [ModelID], type text",
                "    ),",
                "    #\"Derived VariantName\" = Table.AddColumn(",
                "        #\"Added Variant_Master.ModelID\",",
                "        \"VariantName__derived\",",
                "        each [VariantName], type text",
                "    ),",
                "    #\"Removed original VariantName\" = Table.RemoveColumns(",
                "        #\"Derived VariantName\",",
                "        {\"VariantName\"}",
                "    ),",
                "    #\"Replaced VariantName\" = Table.RenameColumns(",
                "        #\"Removed original VariantName\",",
                "        {",
                "            {\"VariantName__derived\", \"VariantName\"}",
                "        }",
                "    )",
                "in",
                "    #\"Replaced VariantName\""
              ]
            }
          }
        ]
      },
      {
        "name": "VIN_Details",
        "columns": [
          {
            "name": "VIN",
            "dataType": "string",
            "sourceColumn": "VIN",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EngineNumber",
            "dataType": "string",
            "sourceColumn": "EngineNumber",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ChassisNumber",
            "dataType": "string",
            "sourceColumn": "ChassisNumber",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductionPlant",
            "dataType": "string",
            "sourceColumn": "ProductionPlant",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductionDate",
            "dataType": "string",
            "sourceColumn": "ProductionDate",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "VIN_Details-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"vin_details.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File VIN_Details.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"VIN\", type text},",
                "        {\"EngineNumber\", type text},",
                "        {\"ChassisNumber\", type text},",
                "        {\"ProductionPlant\", type text},",
                "        {\"ProductionDate\", type date}",
                "        }",
                "    ),",
                "    #\"Derived VIN\" = Table.AddColumn(",
                "        TypedTable,",
                "        \"VIN__derived\",",
                "        each [VIN], type text",
                "    ),",
                "    #\"Removed original VIN\" = Table.RemoveColumns(",
                "        #\"Derived VIN\",",
                "        {\"VIN\"}",
                "    ),",
                "    #\"Replaced VIN\" = Table.RenameColumns(",
                "        #\"Removed original VIN\",",
                "        {",
                "            {\"VIN__derived\", \"VIN\"}",
                "        }",
                "    ),",
                "    #\"Derived EngineNumber\" = Table.AddColumn(",
                "        #\"Replaced VIN\",",
                "        \"EngineNumber__derived\",",
                "        each [EngineNumber], type text",
                "    ),",
                "    #\"Removed original EngineNumber\" = Table.RemoveColumns(",
                "        #\"Derived EngineNumber\",",
                "        {\"EngineNumber\"}",
                "    ),",
                "    #\"Replaced EngineNumber\" = Table.RenameColumns(",
                "        #\"Removed original EngineNumber\",",
                "        {",
                "            {\"EngineNumber__derived\", \"EngineNumber\"}",
                "        }",
                "    ),",
                "    #\"Derived ChassisNumber\" = Table.AddColumn(",
                "        #\"Replaced EngineNumber\",",
                "        \"ChassisNumber__derived\",",
                "        each [ChassisNumber], type text",
                "    ),",
                "    #\"Removed original ChassisNumber\" = Table.RemoveColumns(",
                "        #\"Derived ChassisNumber\",",
                "        {\"ChassisNumber\"}",
                "    ),",
                "    #\"Replaced ChassisNumber\" = Table.RenameColumns(",
                "        #\"Removed original ChassisNumber\",",
                "        {",
                "            {\"ChassisNumber__derived\", \"ChassisNumber\"}",
                "        }",
                "    ),",
                "    #\"Derived ProductionPlant\" = Table.AddColumn(",
                "        #\"Replaced ChassisNumber\",",
                "        \"ProductionPlant__derived\",",
                "        each [ProductionPlant], type text",
                "    ),",
                "    #\"Removed original ProductionPlant\" = Table.RemoveColumns(",
                "        #\"Derived ProductionPlant\",",
                "        {\"ProductionPlant\"}",
                "    ),",
                "    #\"Replaced ProductionPlant\" = Table.RenameColumns(",
                "        #\"Removed original ProductionPlant\",",
                "        {",
                "            {\"ProductionPlant__derived\", \"ProductionPlant\"}",
                "        }",
                "    ),",
                "    #\"Derived ProductionDate\" = Table.AddColumn(",
                "        #\"Replaced ProductionPlant\",",
                "        \"ProductionDate__derived\",",
                "        each [ProductionDate], type text",
                "    ),",
                "    #\"Removed original ProductionDate\" = Table.RemoveColumns(",
                "        #\"Derived ProductionDate\",",
                "        {\"ProductionDate\"}",
                "    ),",
                "    #\"Replaced ProductionDate\" = Table.RenameColumns(",
                "        #\"Removed original ProductionDate\",",
                "        {",
                "            {\"ProductionDate__derived\", \"ProductionDate\"}",
                "        }",
                "    )",
                "in",
                "    #\"Replaced ProductionDate\""
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "Service_History_VehicleID_VIN_Details_VIN",
        "fromTable": "Service_History",
        "fromColumn": "VehicleID",
        "toTable": "VIN_Details",
        "toColumn": "VIN",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "Vehicle_Fact_MASTER_VIN_VIN_Details_VIN",
        "fromTable": "Vehicle_Fact_MASTER",
        "fromColumn": "VIN",
        "toTable": "VIN_Details",
        "toColumn": "VIN",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "Vehicle_Fact_MASTER_ModelName_Model_Master_ModelName",
        "fromTable": "Vehicle_Fact_MASTER",
        "fromColumn": "ModelName",
        "toTable": "Model_Master",
        "toColumn": "ModelName",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "Vehicle_Fact_MASTER_VariantName_Variant_Master_VariantName",
        "fromTable": "Vehicle_Fact_MASTER",
        "fromColumn": "VariantName",
        "toTable": "Variant_Master",
        "toColumn": "VariantName",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "DataSourcePath",
        "kind": "m",
        "expression": [
          "\"https://sorimtechnologies.sharepoint.com\""
        ],
        "annotations": [
          {
            "name": "IsParameterQuery",
            "value": "True"
          },
          {
            "name": "IsParameterQueryRequired",
            "value": "False"
          },
          {
            "name": "PBI_QueryOrder",
            "value": "0"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0"
      },
      {
        "name": "createdBy",
        "value": "QlikAI_Accelerator"
      }
    ]
  }
}