{
  "name": "qlik_sales",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "customers",
        "columns": [
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CustomerName",
            "dataType": "string",
            "sourceColumn": "CustomerName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SignupDate",
            "dataType": "string",
            "sourceColumn": "SignupDate",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "customers-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"customers.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        PromotedHeaders,",
                "        {",
                "        {\"CustomerID\", type text},",
                "        {\"CustomerName\", type text},",
                "        {\"Region\", type text},",
                "        {\"SignupDate\", type date}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "products",
        "columns": [
          {
            "name": "ProductID",
            "dataType": "string",
            "sourceColumn": "ProductID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductName",
            "dataType": "string",
            "sourceColumn": "ProductName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "BasePrice",
            "dataType": "string",
            "sourceColumn": "BasePrice",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "products-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"products.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        PromotedHeaders,",
                "        {",
                "        {\"ProductID\", type text},",
                "        {\"ProductName\", type text},",
                "        {\"Category\", type text},",
                "        {\"BasePrice\", type number}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "region_mapping",
        "columns": [
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "RegionManager",
            "dataType": "string",
            "sourceColumn": "RegionManager",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "region_mapping-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"region_mapping.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        PromotedHeaders,",
                "        {",
                "        {\"Region\", type text},",
                "        {\"RegionManager\", type text}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "qlik_sales",
        "columns": [
          {
            "name": "OrderID",
            "dataType": "string",
            "sourceColumn": "OrderID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductID",
            "dataType": "string",
            "sourceColumn": "ProductID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Channel",
            "dataType": "string",
            "sourceColumn": "Channel",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quantity",
            "dataType": "string",
            "sourceColumn": "Quantity",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "UnitPrice",
            "dataType": "string",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Discount",
            "dataType": "string",
            "sourceColumn": "Discount",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OrderDate",
            "dataType": "string",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SalesAmount",
            "dataType": "string",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "qlik_sales-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"qlik_sales.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        PromotedHeaders,",
                "        {",
                "        {\"OrderID\", type text},",
                "        {\"CustomerID\", type text},",
                "        {\"ProductID\", type text},",
                "        {\"Region\", type text},",
                "        {\"Channel\", type text},",
                "        {\"Category\", type text},",
                "        {\"Quantity\", Int64.Type},",
                "        {\"UnitPrice\", type number},",
                "        {\"Discount\", Int64.Type},",
                "        {\"OrderDate\", type date},",
                "        {\"SalesAmount\", type number}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "qlik_sales_CustomerID_customers_CustomerID",
        "fromTable": "qlik_sales",
        "fromColumn": "CustomerID",
        "toTable": "customers",
        "toColumn": "CustomerID",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "qlik_sales_ProductID_products_ProductID",
        "fromTable": "qlik_sales",
        "fromColumn": "ProductID",
        "toTable": "products",
        "toColumn": "ProductID",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "DataSourcePath",
        "kind": "m",
        "expression": [
          "\"https://sorimtechnologies.sharepoint.com\""
        ],
        "annotations": [
          {
            "name": "IsParameterQuery",
            "value": "True"
          },
          {
            "name": "IsParameterQueryRequired",
            "value": "False"
          },
          {
            "name": "PBI_QueryOrder",
            "value": "0"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0"
      },
      {
        "name": "createdBy",
        "value": "QlikAI_Accelerator"
      }
    ]
  }
}