{
  "name": "Employees",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Employees",
        "columns": [
          {
            "name": "employee_id",
            "dataType": "string",
            "sourceColumn": "employee_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "employee_name",
            "dataType": "string",
            "sourceColumn": "employee_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "department_id",
            "dataType": "string",
            "sourceColumn": "department_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "emp_department_name",
            "dataType": "string",
            "sourceColumn": "emp_department_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "role_id",
            "dataType": "string",
            "sourceColumn": "role_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "location_id",
            "dataType": "string",
            "sourceColumn": "location_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "salary_band_id",
            "dataType": "string",
            "sourceColumn": "salary_band_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "total_hours",
            "dataType": "string",
            "sourceColumn": "total_hours",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "total_days",
            "dataType": "string",
            "sourceColumn": "total_days",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "avg_hours",
            "dataType": "string",
            "sourceColumn": "avg_hours",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "performance_category",
            "dataType": "string",
            "sourceColumn": "performance_category",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Employees-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_employee.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_employee.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    DeptMapFile = Table.SelectRows(",
                "        Source,",
                "        each Text.EndsWith(Text.Lower([Name]), \"dim_department.csv\")",
                "    ){0}[Content],",
                "    DeptMapCsv = Csv.Document(",
                "        DeptMapFile,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    DeptMapHeaders = Table.PromoteHeaders(",
                "        DeptMapCsv,",
                "        [PromoteAllScalars=true]",
                "    ),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"employee_id\", type text},",
                "        {\"department_id\", type text},",
                "        {\"role_id\", type text},",
                "        {\"location_id\", type text},",
                "        {\"salary_band_id\", type text}",
                "        }",
                "    ),",
                "    #\"NestedJoin_DeptMap\" = Table.NestedJoin(",
                "        TypedTable,",
                "        {\"department_id\"},",
                "        DeptMapHeaders,",
                "        {\"department_id\"},",
                "        \"DeptMap_joined\",",
                "        JoinKind.LeftOuter",
                "    ),",
                "    #\"Expand_DeptMap\" = Table.ExpandTableColumn(",
                "        #\"NestedJoin_DeptMap\",",
                "        \"DeptMap_joined\",",
                "        {\"emp_department_name\"},",
                "        {\"emp_department_name\"}",
                "    ),",
                "    #\"ReplaceNulls_DeptMap\" = Table.ReplaceValue(",
                "        #\"Expand_DeptMap\",",
                "        null,",
                "        \"Unknown\",",
                "        Replacer.ReplaceValue,",
                "        {\"emp_department_name\"}",
                "    )",
                "in",
                "    #\"ReplaceNulls_DeptMap\""
              ]
            }
          }
        ]
      },
      {
        "name": "Departments",
        "columns": [
          {
            "name": "department_id",
            "dataType": "string",
            "sourceColumn": "department_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "department_name",
            "dataType": "string",
            "sourceColumn": "department_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Departments-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_department.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_department.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true])",
                "in",
                "    Headers"
              ]
            }
          }
        ]
      },
      {
        "name": "Locations",
        "columns": [
          {
            "name": "location_id",
            "dataType": "string",
            "sourceColumn": "location_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "city",
            "dataType": "string",
            "sourceColumn": "city",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Locations-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_location.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_location.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true])",
                "in",
                "    Headers"
              ]
            }
          }
        ]
      },
      {
        "name": "Projects",
        "columns": [
          {
            "name": "project_id",
            "dataType": "string",
            "sourceColumn": "project_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "client_id",
            "dataType": "string",
            "sourceColumn": "client_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "project_name",
            "dataType": "string",
            "sourceColumn": "project_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "start_date",
            "dataType": "string",
            "sourceColumn": "start_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "end_date",
            "dataType": "string",
            "sourceColumn": "end_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Projects-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_project.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_project.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true])",
                "in",
                "    Headers"
              ]
            }
          }
        ]
      },
      {
        "name": "Clients",
        "columns": [
          {
            "name": "client_id",
            "dataType": "string",
            "sourceColumn": "client_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "client_name",
            "dataType": "string",
            "sourceColumn": "client_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "industry",
            "dataType": "string",
            "sourceColumn": "industry",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Clients-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_client.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_client.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true])",
                "in",
                "    Headers"
              ]
            }
          }
        ]
      },
      {
        "name": "Roles",
        "columns": [
          {
            "name": "role_id",
            "dataType": "string",
            "sourceColumn": "role_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "role_name",
            "dataType": "string",
            "sourceColumn": "role_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Roles-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_role.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_role.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true])",
                "in",
                "    Headers"
              ]
            }
          }
        ]
      },
      {
        "name": "Salary",
        "columns": [
          {
            "name": "salary_band_id",
            "dataType": "string",
            "sourceColumn": "salary_band_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "salary_range",
            "dataType": "string",
            "sourceColumn": "salary_range",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Salary-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_salary_band.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_salary_band.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true])",
                "in",
                "    Headers"
              ]
            }
          }
        ]
      },
      {
        "name": "Performance",
        "columns": [
          {
            "name": "performance_id",
            "dataType": "string",
            "sourceColumn": "performance_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "rating",
            "dataType": "string",
            "sourceColumn": "rating",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Performance-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_performance.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_performance.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true])",
                "in",
                "    Headers"
              ]
            }
          }
        ]
      },
      {
        "name": "Shift",
        "columns": [
          {
            "name": "shift_id",
            "dataType": "string",
            "sourceColumn": "shift_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "shift_type",
            "dataType": "string",
            "sourceColumn": "shift_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Shift-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_shift.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_shift.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true])",
                "in",
                "    Headers"
              ]
            }
          }
        ]
      },
      {
        "name": "Dates",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "full_date",
            "dataType": "string",
            "sourceColumn": "full_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "year",
            "dataType": "string",
            "sourceColumn": "year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "month",
            "dataType": "string",
            "sourceColumn": "month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "day",
            "dataType": "string",
            "sourceColumn": "day",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "quarter",
            "dataType": "string",
            "sourceColumn": "quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dates-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_date.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_date.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"date_id\", type text}",
                "        }",
                "    ),",
                "    Add_full_date = Table.AddColumn(",
                "        TypedTable,",
                "        \"full_date\",",
                "        each try #date(",
                "            Number.FromText(Text.Start([date_id], 4)),",
                "            Number.FromText(Text.Middle([date_id], 4, 2)),",
                "            Number.FromText(Text.End([date_id], 2))",
                "        ) otherwise null,",
                "        type date",
                "    ),",
                "    Add_year = Table.AddColumn(Add_full_date, \"year\", each Date.Year([full_date]), Int64.Type),",
                "    Add_month = Table.AddColumn(Add_year, \"month\", each Date.Month([full_date]), Int64.Type),",
                "    Add_day = Table.AddColumn(Add_month, \"day\", each Date.Day([full_date]), Int64.Type),",
                "    Add_quarter = Table.AddColumn(Add_day, \"quarter\", each \"Q\" & Number.ToText(Date.QuarterOfYear([full_date])), type text)",
                "",
                "in",
                "    Add_quarter"
              ]
            }
          }
        ]
      },
      {
        "name": "Final_Activity",
        "columns": [
          {
            "name": "work_type",
            "dataType": "string",
            "sourceColumn": "work_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "productivity_flag",
            "dataType": "string",
            "sourceColumn": "productivity_flag",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "productivity_score",
            "dataType": "string",
            "sourceColumn": "productivity_score",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "employee_id",
            "dataType": "string",
            "sourceColumn": "employee_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "project_id",
            "dataType": "string",
            "sourceColumn": "project_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "shift_id",
            "dataType": "string",
            "sourceColumn": "shift_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "performance_id",
            "dataType": "string",
            "sourceColumn": "performance_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "activity_id",
            "dataType": "string",
            "sourceColumn": "activity_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "hours_worked",
            "dataType": "string",
            "sourceColumn": "hours_worked",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Final_Activity-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"fact_employee_activity_1m.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File fact_employee_activity_1M.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    Add_work_type = Table.AddColumn(",
                "        Headers,",
                "        \"work_type\",",
                "        each if [hours_worked] > 8 then \"Overtime\" else \"Normal\",",
                "        Int64.Type",
                "    ),",
                "    Add_productivity_flag = Table.AddColumn(",
                "        Add_work_type,",
                "        \"productivity_flag\",",
                "        each if [hours_worked] >= 8 then 1 else 0,",
                "        Int64.Type",
                "    ),",
                "    Add_productivity_score = Table.AddColumn(",
                "        Add_productivity_flag,",
                "        \"productivity_score\",",
                "        each [hours_worked] * 10,",
                "        Int64.Type",
                "    )",
                "in",
                "    Add_productivity_score"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "Employees_department_id_Departments_department_id",
        "fromTable": "Employees",
        "fromColumn": "department_id",
        "toTable": "Departments",
        "toColumn": "department_id",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "Employees_location_id_Locations_location_id",
        "fromTable": "Employees",
        "fromColumn": "location_id",
        "toTable": "Locations",
        "toColumn": "location_id",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "Final_Activity_employee_id_Employees_employee_id",
        "fromTable": "Final_Activity",
        "fromColumn": "employee_id",
        "toTable": "Employees",
        "toColumn": "employee_id",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "Final_Activity_project_id_Projects_project_id",
        "fromTable": "Final_Activity",
        "fromColumn": "project_id",
        "toTable": "Projects",
        "toColumn": "project_id",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "Final_Activity_performance_id_Performance_performance_id",
        "fromTable": "Final_Activity",
        "fromColumn": "performance_id",
        "toTable": "Performance",
        "toColumn": "performance_id",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "Final_Activity_shift_id_Shift_shift_id",
        "fromTable": "Final_Activity",
        "fromColumn": "shift_id",
        "toTable": "Shift",
        "toColumn": "shift_id",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "Final_Activity_date_id_Dates_date_id",
        "fromTable": "Final_Activity",
        "fromColumn": "date_id",
        "toTable": "Dates",
        "toColumn": "date_id",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "Projects_client_id_Clients_client_id",
        "fromTable": "Projects",
        "fromColumn": "client_id",
        "toTable": "Clients",
        "toColumn": "client_id",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "Roles_role_id_Employees_role_id",
        "fromTable": "Roles",
        "fromColumn": "role_id",
        "toTable": "Employees",
        "toColumn": "role_id",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "Employees_salary_band_id_Salary_salary_band_id",
        "fromTable": "Employees",
        "fromColumn": "salary_band_id",
        "toTable": "Salary",
        "toColumn": "salary_band_id",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "DataSourcePath",
        "kind": "m",
        "expression": [
          "\"https://sorimtechnologies.sharepoint.com\""
        ],
        "annotations": [
          {
            "name": "IsParameterQuery",
            "value": "True"
          },
          {
            "name": "IsParameterQueryRequired",
            "value": "False"
          },
          {
            "name": "PBI_QueryOrder",
            "value": "0"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0"
      },
      {
        "name": "createdBy",
        "value": "QlikAI_Accelerator"
      }
    ]
  }
}