{
  "name": "Vehicle_Fact_MASTER",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Vehicle_Fact_MASTER",
        "columns": [
          {
            "name": "ModelName",
            "dataType": "string",
            "sourceColumn": "ModelName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "VIN",
            "dataType": "string",
            "sourceColumn": "VIN",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ServiceType",
            "dataType": "string",
            "sourceColumn": "ServiceType",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "VariantName",
            "dataType": "string",
            "sourceColumn": "VariantName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FuelType",
            "dataType": "string",
            "sourceColumn": "FuelType",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "VehicleChannel",
            "dataType": "string",
            "sourceColumn": "VehicleChannel",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ManufactureYear",
            "dataType": "string",
            "sourceColumn": "ManufactureYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SalePrice",
            "dataType": "string",
            "sourceColumn": "SalePrice",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ServiceDate",
            "dataType": "string",
            "sourceColumn": "ServiceDate",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ServiceCost",
            "dataType": "string",
            "sourceColumn": "ServiceCost",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Vehicle_Fact_MASTER-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"vehicle_fact_master.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File Vehicle_Fact_MASTER.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"VIN\", type text},",
                "        {\"ModelName\", type text},",
                "        {\"VariantName\", type text},",
                "        {\"FuelType\", type text},",
                "        {\"VehicleChannel\", type text},",
                "        {\"ManufactureYear\", Int64.Type},",
                "        {\"SalePrice\", type number},",
                "        {\"ServiceDate\", type date},",
                "        {\"ServiceType\", type text},",
                "        {\"ServiceCost\", type number}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "Dealer_Master",
        "columns": [
          {
            "name": "DealerID-ServiceID",
            "dataType": "string",
            "sourceColumn": "DealerID-ServiceID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DealerName",
            "dataType": "string",
            "sourceColumn": "DealerName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Email",
            "dataType": "string",
            "sourceColumn": "Email",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dealer_Master-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dealer_master.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File Dealer_Master.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"DealerID\", type text},",
                "        {\"DealerName\", type text},",
                "        {\"City\", type text},",
                "        {\"Phone\", type text},",
                "        {\"Email\", type text}",
                "        }",
                "    ),",
                "    #\"Added DealerID-ServiceID\" = Table.AddColumn(",
                "        TypedTable,",
                "        \"DealerID-ServiceID\",",
                "        each [DealerID], type text",
                "    )",
                "in",
                "    #\"Added DealerID-ServiceID\""
              ]
            }
          }
        ]
      },
      {
        "name": "Model_Master",
        "columns": [
          {
            "name": "ModelName",
            "dataType": "string",
            "sourceColumn": "ModelName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ModelID",
            "dataType": "string",
            "sourceColumn": "ModelID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Model_Master-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"model_master.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File Model_Master.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"ModelID\", type text},",
                "        {\"ModelName\", type text}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "Service_History",
        "columns": [
          {
            "name": "ServiceType",
            "dataType": "string",
            "sourceColumn": "ServiceType",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DealerID-ServiceID",
            "dataType": "string",
            "sourceColumn": "DealerID-ServiceID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "VehicleID",
            "dataType": "string",
            "sourceColumn": "VehicleID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ServiceDate",
            "dataType": "string",
            "sourceColumn": "ServiceDate",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ServiceCost",
            "dataType": "string",
            "sourceColumn": "ServiceCost",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Service_History-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"service_history.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File Service_History.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"ServiceID\", type text},",
                "        {\"VehicleID\", type text},",
                "        {\"ServiceDate\", type date},",
                "        {\"ServiceType\", type text},",
                "        {\"ServiceCost\", type number}",
                "        }",
                "    ),",
                "    #\"Added DealerID-ServiceID\" = Table.AddColumn(",
                "        TypedTable,",
                "        \"DealerID-ServiceID\",",
                "        each [ServiceID], type text",
                "    )",
                "in",
                "    #\"Added DealerID-ServiceID\""
              ]
            }
          }
        ]
      },
      {
        "name": "Variant_Master",
        "columns": [
          {
            "name": "VariantName",
            "dataType": "string",
            "sourceColumn": "VariantName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "VariantID",
            "dataType": "string",
            "sourceColumn": "VariantID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ModelID",
            "dataType": "string",
            "sourceColumn": "ModelID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Variant_Master-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"variant_master.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File Variant_Master.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"VariantID\", type text},",
                "        {\"ModelID\", type text},",
                "        {\"VariantName\", type text}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "VIN_Details",
        "columns": [
          {
            "name": "VIN",
            "dataType": "string",
            "sourceColumn": "VIN",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EngineNumber",
            "dataType": "string",
            "sourceColumn": "EngineNumber",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ChassisNumber",
            "dataType": "string",
            "sourceColumn": "ChassisNumber",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductionPlant",
            "dataType": "string",
            "sourceColumn": "ProductionPlant",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductionDate",
            "dataType": "string",
            "sourceColumn": "ProductionDate",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "VIN_Details-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"vin_details.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File VIN_Details.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"VIN\", type text},",
                "        {\"EngineNumber\", type text},",
                "        {\"ChassisNumber\", type text},",
                "        {\"ProductionPlant\", type text},",
                "        {\"ProductionDate\", type date}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "Service_History_DealerID-ServiceID_Dealer_Master_DealerID-ServiceID",
        "fromTable": "Service_History",
        "fromColumn": "DealerID-ServiceID",
        "toTable": "Dealer_Master",
        "toColumn": "DealerID-ServiceID",
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "Vehicle_Fact_MASTER_VIN_VIN_Details_VIN",
        "fromTable": "Vehicle_Fact_MASTER",
        "fromColumn": "VIN",
        "toTable": "VIN_Details",
        "toColumn": "VIN",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "toCardinality": "one"
      },
      {
        "name": "Vehicle_Fact_MASTER_VariantName_Variant_Master_VariantName",
        "fromTable": "Vehicle_Fact_MASTER",
        "fromColumn": "VariantName",
        "toTable": "Variant_Master",
        "toColumn": "VariantName",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "many",
        "toCardinality": "many"
      },
      {
        "name": "Variant_Master_ModelID_Model_Master_ModelID",
        "fromTable": "Variant_Master",
        "fromColumn": "ModelID",
        "toTable": "Model_Master",
        "toColumn": "ModelID",
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "Service_History_ServiceType_Vehicle_Fact_MASTER_ServiceType",
        "fromTable": "Service_History",
        "fromColumn": "ServiceType",
        "toTable": "Vehicle_Fact_MASTER",
        "toColumn": "ServiceType",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "many",
        "toCardinality": "many"
      }
    ],
    "expressions": [
      {
        "name": "DataSourcePath",
        "kind": "m",
        "expression": [
          "\"https://sorimtechnologies.sharepoint.com\""
        ],
        "annotations": [
          {
            "name": "IsParameterQuery",
            "value": "True"
          },
          {
            "name": "IsParameterQueryRequired",
            "value": "False"
          },
          {
            "name": "PBI_QueryOrder",
            "value": "0"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0"
      },
      {
        "name": "createdBy",
        "value": "QlikAI_Accelerator"
      }
    ]
  }
}