{
  "name": "FactSales",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CustomerName",
            "dataType": "string",
            "sourceColumn": "CustomerName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Age",
            "dataType": "string",
            "sourceColumn": "Age",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimCustomer-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"DimCustomer.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        PromotedHeaders,",
                "        {",
                "        {\"CustomerID\", type text},",
                "        {\"CustomerName\", type text},",
                "        {\"Gender\", type text},",
                "        {\"Age\", Int64.Type},",
                "        {\"City\", type text},",
                "        {\"Country\", type text}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "Date",
            "dataType": "string",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DayOfWeek",
            "dataType": "string",
            "sourceColumn": "DayOfWeek",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimDate-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"DimDate.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        PromotedHeaders,",
                "        {",
                "        {\"Date\", type date},",
                "        {\"Year\", Int64.Type},",
                "        {\"Month\", Int64.Type},",
                "        {\"MonthName\", type text},",
                "        {\"Quarter\", type text},",
                "        {\"DayOfWeek\", type text}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "columns": [
          {
            "name": "ProductID",
            "dataType": "string",
            "sourceColumn": "ProductID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductName",
            "dataType": "string",
            "sourceColumn": "ProductName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SubCategory",
            "dataType": "string",
            "sourceColumn": "SubCategory",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "UnitPrice",
            "dataType": "string",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimProduct-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"DimProduct.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        PromotedHeaders,",
                "        {",
                "        {\"ProductID\", type text},",
                "        {\"ProductName\", type text},",
                "        {\"Category\", type text},",
                "        {\"SubCategory\", type text},",
                "        {\"UnitPrice\", type number}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "DimStore",
        "columns": [
          {
            "name": "StoreID",
            "dataType": "string",
            "sourceColumn": "StoreID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StoreName",
            "dataType": "string",
            "sourceColumn": "StoreName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StoreType",
            "dataType": "string",
            "sourceColumn": "StoreType",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimStore-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"DimStore.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        PromotedHeaders,",
                "        {",
                "        {\"StoreID\", type text},",
                "        {\"StoreName\", type text},",
                "        {\"StoreType\", type text},",
                "        {\"City\", type text},",
                "        {\"State\", type text},",
                "        {\"Region\", type text}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "FactSales",
        "columns": [
          {
            "name": "SalesID",
            "dataType": "string",
            "sourceColumn": "SalesID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductID",
            "dataType": "string",
            "sourceColumn": "ProductID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StoreID",
            "dataType": "string",
            "sourceColumn": "StoreID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quantity",
            "dataType": "string",
            "sourceColumn": "Quantity",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "UnitPrice",
            "dataType": "string",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Discount",
            "dataType": "string",
            "sourceColumn": "Discount",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TotalAmount",
            "dataType": "string",
            "sourceColumn": "TotalAmount",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FactSales-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    FileName = \"FactSales.csv\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    FilteredByName = Table.SelectRows(",
                "        Source,",
                "        each Text.Lower([Name]) = Text.Lower(FileName)",
                "    ),",
                "    FilteredByLib = if Table.RowCount(FilteredByName) > 1",
                "        then Table.SelectRows(FilteredByName, each Text.Contains([Folder Path], \"Shared Documents\"))",
                "        else FilteredByName,",
                "    FileBinary = if Table.RowCount(FilteredByLib) = 0",
                "        then error \"File \" & FileName & \" not found under \" & SiteUrl &",
                "             \". Ensure the file exists in SharePoint and credentials are set.\"",
                "        else FilteredByLib{0}[Content],",
                "    CsvData = Csv.Document(",
                "        FileBinary,",
                "        [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]",
                "    ),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        PromotedHeaders,",
                "        {",
                "        {\"SalesID\", type text},",
                "        {\"CustomerID\", type text},",
                "        {\"ProductID\", type text},",
                "        {\"StoreID\", type text},",
                "        {\"Quantity\", Int64.Type},",
                "        {\"UnitPrice\", type number},",
                "        {\"Discount\", Int64.Type},",
                "        {\"TotalAmount\", type number}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "FactSales_CustomerID_DimCustomer_CustomerID",
        "fromTable": "FactSales",
        "fromColumn": "CustomerID",
        "toTable": "DimCustomer",
        "toColumn": "CustomerID",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "FactSales_ProductID_DimProduct_ProductID",
        "fromTable": "FactSales",
        "fromColumn": "ProductID",
        "toTable": "DimProduct",
        "toColumn": "ProductID",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "FactSales_StoreID_DimStore_StoreID",
        "fromTable": "FactSales",
        "fromColumn": "StoreID",
        "toTable": "DimStore",
        "toColumn": "StoreID",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "DataSourcePath",
        "kind": "m",
        "expression": [
          "\"https://sorimtechnologies.sharepoint.com\""
        ],
        "annotations": [
          {
            "name": "IsParameterQuery",
            "value": "True"
          },
          {
            "name": "IsParameterQueryRequired",
            "value": "False"
          },
          {
            "name": "PBI_QueryOrder",
            "value": "0"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0"
      },
      {
        "name": "createdBy",
        "value": "QlikAI_Accelerator"
      }
    ]
  }
}