{
  "name": "Employees",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Employees",
        "columns": [
          {
            "name": "location_id",
            "dataType": "string",
            "sourceColumn": "location_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "role_id",
            "dataType": "string",
            "sourceColumn": "role_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "salary_band_id",
            "dataType": "string",
            "sourceColumn": "salary_band_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "department_id",
            "dataType": "string",
            "sourceColumn": "department_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "employee_id",
            "dataType": "string",
            "sourceColumn": "employee_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "employee_name",
            "dataType": "string",
            "sourceColumn": "employee_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "emp_department_name",
            "dataType": "string",
            "sourceColumn": "emp_department_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "total_hours",
            "dataType": "string",
            "sourceColumn": "total_hours",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "total_days",
            "dataType": "string",
            "sourceColumn": "total_days",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "avg_hours",
            "dataType": "string",
            "sourceColumn": "avg_hours",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "performance_category",
            "dataType": "string",
            "sourceColumn": "performance_category",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Employees-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_employee.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_employee.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"employee_id\", type text},",
                "        {\"department_id\", type text},",
                "        {\"role_id\", type text},",
                "        {\"location_id\", type text},",
                "        {\"salary_band_id\", type text}",
                "        }",
                "    ),",
                "    MergedDepartments = Table.NestedJoin(",
                "        TypedTable,",
                "        {\"department_id\"},",
                "        Departments,",
                "        {\"department_id\"},",
                "        \"Departments\",",
                "        JoinKind.LeftOuter",
                "    ),",
                "    ExpandedDepartments = Table.ExpandTableColumn(",
                "        MergedDepartments,",
                "        \"Departments\",",
                "        {\"department_name\"},",
                "        {\"emp_department_name\"}",
                "    ),",
                "    Filledemp_department_name = Table.ReplaceValue(",
                "        ExpandedDepartments,",
                "        null,",
                "        \"Unknown\",",
                "        Replacer.ReplaceValue,",
                "        {\"emp_department_name\"}",
                "    )",
                "in",
                "    Filledemp_department_name"
              ]
            }
          }
        ]
      },
      {
        "name": "Departments",
        "columns": [
          {
            "name": "department_id",
            "dataType": "string",
            "sourceColumn": "department_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "department_name",
            "dataType": "string",
            "sourceColumn": "department_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Departments-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_department.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_department.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    Columns = Table.ColumnNames(Headers),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        List.Transform(Columns, each {_, type text})",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "Locations",
        "columns": [
          {
            "name": "location_id",
            "dataType": "string",
            "sourceColumn": "location_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "city",
            "dataType": "string",
            "sourceColumn": "city",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Locations-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_location.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_location.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    Columns = Table.ColumnNames(Headers),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        List.Transform(Columns, each {_, type text})",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "Projects",
        "columns": [
          {
            "name": "project_id",
            "dataType": "string",
            "sourceColumn": "project_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "client_id",
            "dataType": "string",
            "sourceColumn": "client_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "project_name",
            "dataType": "string",
            "sourceColumn": "project_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "start_date",
            "dataType": "string",
            "sourceColumn": "start_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "end_date",
            "dataType": "string",
            "sourceColumn": "end_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Projects-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_project.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_project.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    Columns = Table.ColumnNames(Headers),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        List.Transform(Columns, each {_, type text})",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "Clients",
        "columns": [
          {
            "name": "client_id",
            "dataType": "string",
            "sourceColumn": "client_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "client_name",
            "dataType": "string",
            "sourceColumn": "client_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "industry",
            "dataType": "string",
            "sourceColumn": "industry",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Clients-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_client.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_client.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    Columns = Table.ColumnNames(Headers),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        List.Transform(Columns, each {_, type text})",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "Roles",
        "columns": [
          {
            "name": "role_id",
            "dataType": "string",
            "sourceColumn": "role_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "role_name",
            "dataType": "string",
            "sourceColumn": "role_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Roles-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_role.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_role.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    Columns = Table.ColumnNames(Headers),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        List.Transform(Columns, each {_, type text})",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "Salary",
        "columns": [
          {
            "name": "salary_band_id",
            "dataType": "string",
            "sourceColumn": "salary_band_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "salary_range",
            "dataType": "string",
            "sourceColumn": "salary_range",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Salary-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_salary_band.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_salary_band.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    Columns = Table.ColumnNames(Headers),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        List.Transform(Columns, each {_, type text})",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "Performance",
        "columns": [
          {
            "name": "performance_id",
            "dataType": "string",
            "sourceColumn": "performance_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "rating",
            "dataType": "string",
            "sourceColumn": "rating",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Performance-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_performance.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_performance.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    Columns = Table.ColumnNames(Headers),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        List.Transform(Columns, each {_, type text})",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "Shift",
        "columns": [
          {
            "name": "shift_id",
            "dataType": "string",
            "sourceColumn": "shift_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "shift_type",
            "dataType": "string",
            "sourceColumn": "shift_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Shift-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_shift.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_shift.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    Columns = Table.ColumnNames(Headers),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        List.Transform(Columns, each {_, type text})",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "Dates",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "full_date",
            "dataType": "string",
            "sourceColumn": "full_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "year",
            "dataType": "string",
            "sourceColumn": "year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "month",
            "dataType": "string",
            "sourceColumn": "month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "day",
            "dataType": "string",
            "sourceColumn": "day",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "quarter",
            "dataType": "string",
            "sourceColumn": "quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dates-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"dim_date.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File dim_date.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    TypedTable = Table.TransformColumnTypes(",
                "        Headers,",
                "        {",
                "        {\"date_id\", type text}",
                "        }",
                "    )",
                "in",
                "    TypedTable"
              ]
            }
          }
        ]
      },
      {
        "name": "Final_Activity",
        "columns": [
          {
            "name": "employee_id",
            "dataType": "string",
            "sourceColumn": "employee_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "project_id",
            "dataType": "string",
            "sourceColumn": "project_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "shift_id",
            "dataType": "string",
            "sourceColumn": "shift_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "performance_id",
            "dataType": "string",
            "sourceColumn": "performance_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "activity_id",
            "dataType": "string",
            "sourceColumn": "activity_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "hours_worked",
            "dataType": "string",
            "sourceColumn": "hours_worked",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "work_type",
            "dataType": "string",
            "sourceColumn": "work_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "productivity_flag",
            "dataType": "string",
            "sourceColumn": "productivity_flag",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "productivity_score",
            "dataType": "string",
            "sourceColumn": "productivity_score",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Final_Activity-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    SiteUrl = \"https://sorimtechnologies.sharepoint.com\",",
                "    Source = SharePoint.Files(SiteUrl, [ApiVersion = 15]),",
                "    Filtered = Table.SelectRows(",
                "        Source,",
                "        each",
                "            Text.EndsWith(Text.Lower([Name]), \"fact_employee_activity_1m.csv\") and",
                "            Text.Contains(Text.Lower([Folder Path]), \"shared documents\")",
                "    ),",
                "    File = if Table.RowCount(Filtered) > 0",
                "        then Filtered{0}[Content]",
                "        else error \"File fact_employee_activity_1M.csv not found in SharePoint\",",
                "    Csv = Csv.Document(File, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),",
                "    Add_productivity_score = Table.AddColumn(",
                "        Headers,",
                "        \"productivity_score\",",
                "        each [hours_worked] * 10,",
                "        type number",
                "    )",
                "in",
                "    Add_productivity_score"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [],
    "expressions": [
      {
        "name": "DataSourcePath",
        "kind": "m",
        "expression": [
          "\"https://sorimtechnologies.sharepoint.com\""
        ],
        "annotations": [
          {
            "name": "IsParameterQuery",
            "value": "True"
          },
          {
            "name": "IsParameterQueryRequired",
            "value": "False"
          },
          {
            "name": "PBI_QueryOrder",
            "value": "0"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0"
      },
      {
        "name": "createdBy",
        "value": "QlikAI_Accelerator"
      }
    ]
  }
}