erDiagram
    OEM_All_corrected {
        ModelName string
        VariantName string
        DealerName string
        ServiceType string
        VIN string
        EngineNumber string
        ChassisNumber string
        ServiceDate decimal
        ServiceCost decimal
        VehicleChannel string
    }
    Oem_Dealer_Master {
        DealerName string
        DealerID decimal
        Oem_Dealer_Master_City string
        Phone string
        Email string
    }
    Oem_Model_Master {
        ModelName string
        ModelID decimal
    }
    Oem_Service_History {
        ServiceType string
        ServiceID decimal
        VehicleID decimal
        Oem_Service_History_ServiceDate decimal
        Oem_Service_History_ServiceCost decimal
    }
    Oem_Variant_Master {
        VariantName string
        VariantID decimal
        Oem_Variant_Master_ModelID decimal
    }
    OEM_All_corrected }o--|| Oem_Dealer_Master : "95%"
    OEM_All_corrected }o--|| Oem_Model_Master : "95%"
    OEM_All_corrected }o--|| Oem_Service_History : "95%"
    OEM_All_corrected }o--|| Oem_Variant_Master : "95%"